name: mineralmap
channels:
  - conda-forge
dependencies:
  - python=3.10
  - rasterio
  - gdal
  - geopandas
  - numpy
  - scipy
  - pandas
  - scikit-learn
  - matplotlib
  - pyyaml
  - jupyterlab
  - pip
  - pip:
      - -e .
